### PR TITLE
add epsilon to RankCrossEntropyLoss to avoid NAN

### PR DESCRIPTION
**Pull request by jibrilfrej**

### CODE REVIEW

**Comment by uduse** [comment]
@jibrilfrej It's ok to merge with to approved reviews, and I just invited you as a collaborator. Feel free to merge it once you accept the invitation.

**Comment by jibrilfrej** [comment]
I accepted the invitation but I still cannot merge.

**Comment by uduse** [comment]
Oh it's my fault. I forgot the master is protected. Would you mind making the change on branch `2.2-dev` instead?

**Comment by jibrilfrej** [comment]
I created a new pull request : #779

**Pull request closed without merging**
