### PR TITLE
Feature/update wikiqa tutorial

### PR DESCRIPTION
**Pull request by uduse**

### CODE REVIEW

**Comment by pl8787** [comment]
How about print some process information, when running `init.ipynb`? such as parameters have been generated.

**Comment by faneshion** [comment]
ModuleNotFoundError: No module named 'tabulate'

**Comment by uduse** [comment]
@faneshion Right now we don't separate dev packages (packages user do not need), so dev packages like `tabulate` are just ignored.

**Comment by faneshion** [comment]
Okay~

**Pull request merged**
