### PR TITLE
Feature/bimpm add Bimpm Model

### PR DESCRIPTION
**Pull request by rgtjf**
#183 Not done yet.

### CODE REVIEW

**Comment by rgtjf** [comment]
1. bug1: left_length = right_length = 40
2. bug2: 
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [36,40,256] vs. [36,36,256]
	 [[Node: multi_perspective_layer_1/mp_max_attentive_match_1/mul = Mul[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/AddN_60"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](bidirectional_1_1/concat, multi_perspective_layer_1/mp_max_attentive_match_1/GatherNd)]]
``

```
import keras
import pandas as pd
import numpy as np
import matchzoo as mz

train_pack = mz.datasets.wiki_qa.load_data('train', task='ranking')
valid_pack = mz.datasets.wiki_qa.load_data('dev', task='ranking', filter=True)
predict_pack = mz.datasets.wiki_qa.load_data('test', task='ranking', filter=True)
## Note that fixed_length_left == fixed_length_right
preprocessor = mz.preprocessors.BasicPreprocessor(fixed_length_left=40, fixed_length_right=40, remove_stop_words=True)
train_pack_processed = preprocessor.fit_transform(train_pack)

valid_pack_processed = preprocessor.transform(valid_pack)
predict_pack_processed = preprocessor.transform(predict_pack)

ranking_task = mz.tasks.Ranking(loss=mz.losses.RankHingeLoss())
ranking_task.metrics = [
    mz.metrics.NormalizedDiscountedCumulativeGain(k=3),
    mz.metrics.NormalizedDiscountedCumulativeGain(k=5),
    mz.metrics.MeanAveragePrecision()
]

model = mz.contrib.models.BimpmModel()
model.params['input_shapes'] = preprocessor.context['input_shapes']
model.params['task'] = ranking_task
model.params['embedding_input_dim'] = preprocessor.context['vocab_size'] + 1
model.params['embedding_output_dim'] = 300
model.params['embedding_trainable'] = True
model.params['optimizer'] = 'adam'
model.params['dropout_rate'] = 0.1
model.guess_and_fill_missing_params()
model.build()
model.compile()
model.backend.summary()

glove_embedding = mz.datasets.embeddings.load_glove_embedding(dimension=300)
embedding_matrix = glove_embedding.build_matrix(preprocessor.context['vocab_unit'].state['term_index'])

train_generator = mz.DPoolPairDataGenerator(train_pack_processed,
                                            fixed_length_left=10,
                                            fixed_length_right=40,
                                            num_dup=2,
                                            num_neg=1,
                                            batch_size=20)
len(train_generator)

predict_generator = mz.DPoolDataGenerator(predict_pack_processed,
                                          fixed_length_left=10,
                                          fixed_length_right=40,
                                          batch_size=20)
len(predict_generator)

pred_x, pred_y = predict_generator[:-1]
evaluate = mz.callbacks.EvaluateAllMetrics(model, x=pred_x, y=pred_y, batch_size=len(pred_y))
print(len(pred_y))
print(len(pred_x))
print(pred_x.keys())

history = model.fit_generator(train_generator, epochs=20, callbacks=[evaluate], workers=3, use_multiprocessing=True)
```

**Comment by rgtjf** [comment]
```
Epoch 2/20
170/170 [==============================] - 409s 2s/step - loss: 0.1141
Validation: normalized_discounted_cumulative_gain@3(0.0): 0.49181854796744756 - normalized_discounted_cumulative_gain@5(0.0): 0.5562213679734096 - mean_average_precision(0.0): 0.
5150238963759117
Epoch 3/20
170/170 [==============================] - 410s 2s/step - loss: 0.0272
Validation: normalized_discounted_cumulative_gain@3(0.0): 0.4844153047954907 - normalized_discounted_cumulative_gain@5(0.0): 0.5562059216769885 - mean_average_precision(0.0): 0.5
118042727072002
....
Epoch 19/20
170/170 [==============================] - 416s 2s/step - loss: 0.0054
Validation: normalized_discounted_cumulative_gain@3(0.0): 0.4692734305831182 - normalized_discounted_cumulative_gain@5(0.0): 0.53684762913571 - mean_average_precision(0.0): 0.5034001738245315
Epoch 20/20
170/170 [==============================] - 419s 2s/step - loss: 0.0088
Validation: normalized_discounted_cumulative_gain@3(0.0): 0.4799752474945343 - normalized_discounted_cumulative_gain@5(0.0): 0.5421306263492612 - mean_average_precision(0.0): 0.49918934439032153
```

**Comment by faneshion** [comment]
Please close this PR, and reopen it to merge it into 2.1-dev branch.

**Comment by rgtjf** [comment]
move to https://github.com/NTMC-Community/MatchZoo/pull/669 and close.

**Pull request closed without merging**
