### PR TITLE
add support for keras 2.3

### LINKED ISSUE #789: Tensorflow2.0目前是否全面支持？
如题，我目前的运行环境使用是tf2.0版本，keras是为2.3.0。
但无法执行
报错信息如下：
```
~/anaconda3/lib/python3.7/site-packages/keras/engine/training.py in _prepare_total_loss(self, masks)
    690 
    691                     output_loss = loss_fn(
--> 692                         y_true, y_pred, sample_weight=sample_weight)
    693 
    694                 if len(self.outputs) > 1:

TypeError: __call__() got an unexpected keyword argument 'sample_weight'
```

### PR DESCRIPTION
**Pull request by matthew-z**
* make losses inherit `keras.losses.Loss`
* replace some `keras.backend.tf` with `tf` (K.tf does not exist anymore as keras is going to be synced with tf.keras and drop multi-backend)

We may consider to replace `keras` with `tf.keras` in the future.

fix #789

### CODE REVIEW

**Comment by matthew-z** [comment]
somehow the CI failed because it failed to install tensorflow==2.0.0

**Comment by uduse** [comment]
instead of using `2.0.0`, choose one version from: `2.0.0a0`, `2.0.0b0`, `2.0.0b1`

**Comment by matthew-z** [comment]
`2.0.0` official version has been released, but the pip used in trusty is too old to install it. I will add commands to upgrade `pip` in the `.travis.yml` and have a try again.

**Comment by matthew-z** [comment]
OK, CI passed

**Comment by uduse** [comment]
Wait, this is not on dev branch... You are supposed to make changes on branch `2.2-dev`. Could you please do so?

**Comment by uduse** [comment]
I guess after this PR is merged, we will release a `2.3` version.

**Comment by matthew-z** [comment]
OK I will rebase to dev-2.2 and open a new PR

**Pull request closed without merging**
