### PR TITLE
Feature/filtered_preprocessor

### PR DESCRIPTION
**Pull request by jellying**
Add a filtering process to the preprocessor.transform function, to avoid generating 0-length text in data_pack, which may cause an exception to the rnn model.

### CODE REVIEW

**Comment by jellying** [comment]
> A BETTER OPTIONS IS TO CREATE A PROCESSOR UNIT.

I attempt to implement it by creating a Unit like punc_removal class, but I think these units are text-level processor. The filter processor needs to be applied on whole data_pack.

**Comment by bwanglzu** [comment]
@jellying can you update `FrequencyFilterUnit`? we have several processors like `BasicProcessor`, and change one of the instance doesn't really solve the issue.

**Comment by jellying** [comment]
> @jellying can you update `FrequencyFilterUnit`? we have several processors like `BasicProcessor`, and change one of the instance doesn't really solve the issue.

I see. I think adding a filter function in basic class base_preprocessor can solve it. I can update it. Can I change the filter strategy and keep at least one word in each text? Or if there is a better method to avoid 0-length text exist in data_pack.

**Comment by uduse** [comment]
I recommend adding a new unit for this. All units should have minimum functionalities.

**Comment by bwanglzu** [comment]
me either

**Pull request closed without merging**
