### PR TITLE
add new function on datapack

### PR DESCRIPTION
**Pull request by faneshion**
add more function for datapack~

### CODE REVIEW

**Comment by uduse** [comment]
Call `apply_on_left/right` in `apply_on_text`.

**Comment by faneshion** [comment]
@uduse It cannot be implemented as you said. Because the `apply_on_left` and `apply_on_right` both return a new `pack`, and the `apply_on_text` cannot deal with the return value.

**Comment by uduse** [comment]
Just added this commit https://github.com/NTMC-Community/MatchZoo/commit/ddebdde368cbe5dfb954f06a40bfa1ce0cd302b3

**Comment by faneshion** [comment]
Done~

**Pull request merged**
